WIP: APP-1316: Parcels: Update SDK in accordance to Itella endpoints
paysera/kotlin-lib-parcel-sdk pull request #6
Opened 2021-07-09 08:25 UTC by gilbertparreno

2021-07-10 12:35 UTC, vaidadry commented on src/main/kotlin/com/paysera/lib/parcel/retrofit/NetworkApiClient.kt
> +    fun getUser(): Deferred<PSPackageUser>
`getUser()` - also returns this field : `val suspended: Boolean`  in `PSPackageUser`- need to update SDK entity

2021-07-10 12:35 UTC, vaidadry commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSTerminal.kt
>  data class PSTerminal(
`PSTerminal` in responses  also returns this field `val model: String`

2021-07-10 12:35 UTC, vaidadry commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSCell.kt
> +data class PSCell(
`PSCell` in response has more fields than currently defined in SDK entity

2021-07-10 12:35 UTC, vaidadry commented on src/main/kotlin/com/paysera/lib/parcel/clients/ParcelApiClient.kt
>  import com.paysera.lib.parcel.entities.filters.PSTerminalsFilter
`PSTerminalsFilter` has more fields in comparison to SWIFT sdk

2021-07-10 12:35 UTC, vaidadry commented on src/test/kotlin/com/paysera/lib/parcel/clients/ParcelTest.kt
> +    @Test
`getPackage()` fails because -  `PSPackage`  field `statusChanges ` is not correct in entity - thats from response (test passes if edited). Also response has more fields  than currently defined in entity, though not failing tests

"status_changes": {
	"items":[
		{
			"status":"return_requested",
			"created_at":1625914547
		}
	]
}

2021-07-10 12:35 UTC, vaidadry commented on src/main/kotlin/com/paysera/lib/parcel/clients/ParcelApiClient.kt
> +    fun getTerminalCells(terminalId: String) = networkApiClient.getTerminalCells(terminalId)
`getTerminalCells()` fails with error 
{"error":"unauthorized","error_description":"Wrong or no token provided"}
although other tests pass

2021-07-10 12:35 UTC, vaidadry commented on src/test/kotlin/com/paysera/lib/parcel/clients/ParcelTest.kt
> +    fun providePackage() {
`providePackage()` fails with  INFO: {"error":"access_denied","error_description":"Wrong access token provided"}

2021-07-12 01:12 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSCell.kt
> +data class PSCell(
where did you see these missing fields? As per checking I already have the same fields with swift-parcel-sdk.

2021-07-12 05:21 UTC, vaidadry commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSCell.kt
> +data class PSCell(
https://parcel-api.paysera.net/public/rest/v1/packages/Hiy_sF9gUK9LPEDLieixhcO0SflDGx2br see the response of getPackage()

2021-07-12 06:21 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSCell.kt
> +data class PSCell(
We can just omit some fields which aren't in use for now :)

2021-07-12 06:50 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/retrofit/NetworkApiClient.kt
> +    fun getUser(): Deferred<PSPackageUser>
let's match our fields with iOS, let just add those missing fields once needed.

2021-07-12 06:51 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSTerminal.kt
>  data class PSTerminal(
same here

2021-07-12 06:51 UTC, gilbertparreno commented on src/test/kotlin/com/paysera/lib/parcel/clients/ParcelTest.kt
> +    @Test
fixed :)

2021-07-12 06:52 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/clients/ParcelApiClient.kt
> +    fun getTerminalCells(terminalId: String) = networkApiClient.getTerminalCells(terminalId)
I got this error too :(

2021-07-14 16:36 UTC, eunicegalang requested changes
Also, please check all Entities that has unnecessary commas

2021-07-14 16:36 UTC, eunicegalang commented on src/test/kotlin/com/paysera/lib/parcel/clients/ParcelTest.kt
> +        val response = apiClient.getPackages(PSPackageFilter()).runCatchingBlocking()
Create a dummy data with Pending status

2021-07-14 16:49 UTC, eunicegalang requested changes

2021-07-14 16:49 UTC, eunicegalang commented on src/main/kotlin/com/paysera/lib/parcel/retrofit/NetworkApiClient.kt
> +        @Query("statuses") statuses: List<String>?,
@Query("statuses[]") statuses: List<String>?,

2021-07-16 01:21 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSPackagePaymentStatus.kt
> +    @SerializedName("canceled")
but the spelled that as **canceled**

2021-07-16 01:21 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSPackagePaymentStatus.kt
> +    CANCELED("canceled")
here too

2021-07-16 01:23 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSPackage.kt
> +    val status: PSPackageStatus?
its **required** but I made an enum so we could easily get its value and make sure that it will just return null just in case the status doesn't match any of our enum values.

2021-07-16 01:24 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSPackagePayment.kt
> +    val status: PSPackagePaymentStatus?
same here

2021-07-16 01:25 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSStatusChange.kt
> +    val status: PSPackageStatus?,
same here

2021-07-16 01:25 UTC, eunicegalang commented on src/main/kotlin/com/paysera/lib/parcel/clients/ParcelApiClient.kt
> +    fun getTerminalCells(terminalId: String) = networkApiClient.getTerminalCells(terminalId)
c

2021-07-16 01:25 UTC, eunicegalang commented on src/test/kotlin/com/paysera/lib/parcel/clients/ParcelTest.kt
> +    fun providePackage() {
please add /refresh-token endpoint instead

2021-07-16 02:04 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/retrofit/NetworkApiClient.kt
> +        @Query("statuses") statuses: List<String>?,
fixed

2021-07-16 02:04 UTC, gilbertparreno commented on src/test/kotlin/com/paysera/lib/parcel/clients/ParcelTest.kt
> +        val response = apiClient.getPackages(PSPackageFilter()).runCatchingBlocking()
fixed

2021-07-16 02:05 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSPackage.kt
>      val createdAt: Date?,
fixed

2021-07-16 02:06 UTC, gilbertparreno commented
I added `refresh-token` api but still not working for me, would you give it a try @eunicegalang ?

2021-07-16 07:37 UTC, eunicegalang commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSPackage.kt
> +    val status: PSPackageStatus?
This should never be null.
```
status: required(one of xxx, xxx, xxx, default: pending)
The package status
```

2021-07-16 07:38 UTC, eunicegalang commented
> I added `refresh-token` api but still not working for me, would you give it a try @eunicegalang ?

yep, this should work for accounts tagged as courier :)

2021-07-16 07:43 UTC, eunicegalang commented on src/test/kotlin/com/paysera/lib/parcel/clients/ParcelTest.kt
> +        val request = PSCourierCompanyTokenRequest("CONDN4XAG34Ifa3QV58TK03hAl__pBYRZj")
`private val courierCompany = "CONDN4XAG34Ifa3QV58TK03hAl__pBYRZj"` and place it above :)

2021-07-16 07:52 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSPackage.kt
> +    val status: PSPackageStatus?
yes but sometimes the backend team made changes without letting us know.

2021-07-16 11:28 UTC, eunicegalang commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSPackage.kt
> +    val status: PSPackageStatus?
Yep, but let's follow the spec as it is indicated as required. We can make Pending as default if needed.

2021-07-19 04:53 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/parcel/entities/PSPackage.kt
> +    val status: PSPackageStatus?
fixed :)

2021-07-19 07:34 UTC, merged